### PR TITLE
Update url and regex

### PR DESCRIPTION
**Pull request by adamvallee**
The source that you ship with the superfecta module doesn't work. I sent this in on Feb 28th and you have done nothing to correct this. Why include broken modules, and I am not able to update it on my servers because it is unsigned.

### CODE REVIEW

**Comment by adamvallee** [comment]
This is a simple fix, why does it take months for issues to be corrected?

**Comment by jfinstrom** [comment]
> This is a simple fix, why does it take months for issues to be corrected?

All code submissions require a CLA: http://wiki.freepbx.org/display/FOP/Code+License+Agreement

**Comment by adamvallee** [comment]
Thats fine, someone working for the company can "submit it" it is a broken
source in a module that they provide in software that they are making money
off of, they can figure it out. Im not filling out any forms or signing
anything. They know it doesn't work... They need to fix it...

**Comment by jfinstrom** [comment]
This is a Open Source GPL module it is not sold. No money is made off these modules and the sources are generally community maintained. If a source is broken and nobody wants to fix it the source may get removed.

**Pull request closed without merging**
